# Generated by Django 5.2 on 2025-05-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joy_soni', models.PositiveIntegerField()),
                ('joylashuv', models.CharField(max_length=255)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='fields/')),
            ],
        ),
    ]
