# Generated by Django 5.2 on 2025-05-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='owner',
        ),
    ]
