# Generated by Django 5.2 on 2025-05-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('qolgan_joy', models.PositiveIntegerField(blank=True, default=0)),
                ('maydon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.field')),
            ],
        ),
    ]
