# Generated by Django 5.2 on 2025-05-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sana',
            field=models.DateTimeField(),
        ),
    ]
