# Generated by Django 5.2 on 2025-05-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('fields', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='maydon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.field'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
