# Generated by Django 5.2 on 2025-05-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='maydon',
        ),
    ]
