# Generated by Django 5.2 on 2025-05-28 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_maydon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='soni',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
